// Mocks generated by Mockito 5.4.5 from annotations
// in kagi_news/test/data/repository/kagi_news_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kagi_news/data/datasource/local/kagi_news_local_data_source.dart'
    as _i4;
import 'package:kagi_news/data/datasource/network/kagi_news_api_service.dart'
    as _i6;
import 'package:kagi_news/data/datasource/network/model/news_categories_response.dart'
    as _i2;
import 'package:kagi_news/data/datasource/network/model/news_category_details_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKagiNewsCategoriesResponse_0 extends _i1.SmartFake
    implements _i2.KagiNewsCategoriesResponse {
  _FakeKagiNewsCategoriesResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNewsCategoryDetailsResponse_1 extends _i1.SmartFake
    implements _i3.NewsCategoryDetailsResponse {
  _FakeNewsCategoryDetailsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KagiNewsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockKagiNewsLocalDataSource extends _i1.Mock
    implements _i4.KagiNewsLocalDataSource {
  MockKagiNewsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int?> getLastSavedTimestamp() => (super.noSuchMethod(
        Invocation.method(
          #getLastSavedTimestamp,
          [],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<void> saveTimestamp(int? timestamp) => (super.noSuchMethod(
        Invocation.method(
          #saveTimestamp,
          [timestamp],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.KagiNewsCategoriesResponse?> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i5.Future<_i2.KagiNewsCategoriesResponse?>.value(),
      ) as _i5.Future<_i2.KagiNewsCategoriesResponse?>);

  @override
  _i5.Future<void> saveCategories(_i2.KagiNewsCategoriesResponse? categories) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCategories,
          [categories],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.NewsCategoryDetailsResponse?> getCategoryDetails(
          String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryDetails,
          [fileName],
        ),
        returnValue: _i5.Future<_i3.NewsCategoryDetailsResponse?>.value(),
      ) as _i5.Future<_i3.NewsCategoryDetailsResponse?>);

  @override
  _i5.Future<void> saveCategoryDetails(
    String? fileName,
    String? category,
    _i3.NewsCategoryDetailsResponse? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCategoryDetails,
          [
            fileName,
            category,
            details,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.NewsCategoryDetailsResponse>> getAllCategoryDetails() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategoryDetails,
          [],
        ),
        returnValue: _i5.Future<List<_i3.NewsCategoryDetailsResponse>>.value(
            <_i3.NewsCategoryDetailsResponse>[]),
      ) as _i5.Future<List<_i3.NewsCategoryDetailsResponse>>);

  @override
  _i5.Future<_i3.NewsCategoryDetailsResponse?> getCategoryDetailsByName(
          String? categoryName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryDetailsByName,
          [categoryName],
        ),
        returnValue: _i5.Future<_i3.NewsCategoryDetailsResponse?>.value(),
      ) as _i5.Future<_i3.NewsCategoryDetailsResponse?>);

  @override
  _i5.Future<void> clearAllCategoryDetails() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCategoryDetails,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [KagiNewsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKagiNewsApiService extends _i1.Mock
    implements _i6.KagiNewsApiService {
  MockKagiNewsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.KagiNewsCategoriesResponse> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i5.Future<_i2.KagiNewsCategoriesResponse>.value(
            _FakeKagiNewsCategoriesResponse_0(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i5.Future<_i2.KagiNewsCategoriesResponse>);

  @override
  _i5.Future<_i3.NewsCategoryDetailsResponse> getCategoryDetails(
          String? fileName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryDetails,
          [fileName],
        ),
        returnValue: _i5.Future<_i3.NewsCategoryDetailsResponse>.value(
            _FakeNewsCategoryDetailsResponse_1(
          this,
          Invocation.method(
            #getCategoryDetails,
            [fileName],
          ),
        )),
      ) as _i5.Future<_i3.NewsCategoryDetailsResponse>);
}
