// Mocks generated by Mockito 5.4.5 from annotations
// in kagi_news/test/ui/kagi_news_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kagi_news/data/datasource/network/model/news_categories_response.dart'
    as _i5;
import 'package:kagi_news/data/datasource/network/model/news_category_details_response.dart'
    as _i6;
import 'package:kagi_news/data/datasource/repository/kagi_news_repository.dart'
    as _i3;
import 'package:kagi_news/data/datasource/repository/result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [KagiNewsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKagiNewsRepository extends _i1.Mock
    implements _i3.KagiNewsRepository {
  MockKagiNewsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<bool>> sync() => (super.noSuchMethod(
        Invocation.method(
          #sync,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #sync,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);

  @override
  _i4.Future<_i2.Result<_i5.KagiNewsCategoriesResponse>> getCategories(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i4.Future<_i2.Result<_i5.KagiNewsCategoriesResponse>>.value(
                _FakeResult_0<_i5.KagiNewsCategoriesResponse>(
          this,
          Invocation.method(
            #getCategories,
            [],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.KagiNewsCategoriesResponse>>);

  @override
  _i4.Future<_i2.Result<_i6.NewsCategoryDetailsResponse>> getCategoryDetails(
    String? fileName, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryDetails,
          [fileName],
          {#forceRefresh: forceRefresh},
        ),
        returnValue:
            _i4.Future<_i2.Result<_i6.NewsCategoryDetailsResponse>>.value(
                _FakeResult_0<_i6.NewsCategoryDetailsResponse>(
          this,
          Invocation.method(
            #getCategoryDetails,
            [fileName],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i4.Future<_i2.Result<_i6.NewsCategoryDetailsResponse>>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
